import { File, FileType } from "../../api/File/types";

export const rows: File[] = [
  {
    id: "1",
    name: "File1",
    type: FileType.DIR,
    access_link: "link1",
    size: 100,
    path: "",
    root: false,
  },
  {
    id: "2",
    name: "File2",
    type: FileType.TXT,
    access_link: "link2",
    size: 200,
    path: "",
    root: false,
  },
  {
    id: "3",
    name: "File3",
    type: FileType.IMG,
    access_link: "link3",
    size: 300,
    path: "",
    root: false,
  },
  {
    id: "4",
    name: "File4",
    type: FileType.MP3,
    access_link: "link4",
    size: 400,
    path: "",
    root: false,
  },
  {
    id: "5",
    name: "File5",
    type: FileType.MP4,
    access_link: "link5",
    size: 500,
    path: "",
    root: false,
  },
  {
    id: "6",
    name: "File6",
    type: FileType.ZIP,
    access_link: "link6",
    size: 600,
    path: "",
    root: false,
  },
  {
    id: "7",
    name: "File7",
    type: FileType.ANY,
    access_link: "link7",
    size: 700,
    path: "",
    root: false,
  },
];
